"""empty message

Revision ID: 102642694328
Revises: bc71f2b38476
Create Date: 2023-08-28 18:15:27.349594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102642694328'
down_revision = 'bc71f2b38476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_type', ['class_number'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
