"""empty message

Revision ID: 2803a261e851
Revises: 80bd9458d088
Create Date: 2023-09-06 17:01:14.012987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2803a261e851'
down_revision = '80bd9458d088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_classes')
    # ### end Alembic commands ###
