"""empty message

Revision ID: 2bd7e67886d8
Revises: cdceb46ddaaf
Create Date: 2023-10-04 23:24:42.805165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd7e67886d8'
down_revision = 'cdceb46ddaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_lesson', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_table', schema=None) as batch_op:
        batch_op.drop_column('flow_lesson')

    # ### end Alembic commands ###
