"""empty message

Revision ID: 3b001e6abd5f
Revises: 69417df85ce6
Create Date: 2023-09-07 21:24:23.735268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b001e6abd5f'
down_revision = '69417df85ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_count', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_list', schema=None) as batch_op:
        batch_op.drop_column('lesson_count')

    # ### end Alembic commands ###
