"""empty message

Revision ID: 3ece44f672ff
Revises: 8b2b1de22cab
Create Date: 2023-09-07 21:55:31.950605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ece44f672ff'
down_revision = '8b2b1de22cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_time', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['lesson_time'], ['time_list.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_table_day_lessons',
    sa.Column('time_table_day_id', sa.Integer(), nullable=True),
    sa.Column('daily_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_table_id'], ['daily_table.id'], ),
    sa.ForeignKeyConstraint(['time_table_day_id'], ['time_table_day.id'], )
    )
    op.drop_table('daily_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flow_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name='daily_time_class_id_fkey'),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name='daily_time_flow_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='daily_time_room_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='daily_time_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_time_pkey')
    )
    op.drop_table('time_table_day_lessons')
    op.drop_table('daily_table')
    # ### end Alembic commands ###
