"""empty message

Revision ID: 46edb0c27224
Revises: 4bf358899cc0
Create Date: 2023-08-29 22:02:05.384727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46edb0c27224'
down_revision = '4bf358899cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_month_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_month_payments', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('real_price')

    # ### end Alembic commands ###
