"""empty message

Revision ID: 4bf358899cc0
Revises: 76a5d95d4f58
Create Date: 2023-08-28 21:10:08.817826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf358899cc0'
down_revision = '76a5d95d4f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('discount_type_id', sa.Integer(), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discount_type_id'], ['discount_type.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_discount')
    op.drop_table('discount_type')
    # ### end Alembic commands ###
