"""empty message

Revision ID: 69417df85ce6
Revises: d700966dcde7
Create Date: 2023-09-07 21:23:43.478073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69417df85ce6'
down_revision = 'd700966dcde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_list', schema=None) as batch_op:
        batch_op.drop_column('lesson_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_count', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
