"""empty message

Revision ID: 76a5d95d4f58
Revises: a87f68e5e5d9
Create Date: 2023-08-28 18:18:01.702459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a5d95d4f58'
down_revision = 'a87f68e5e5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'class_type', ['class_number'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('class_number')

    # ### end Alembic commands ###
