"""empty message

Revision ID: 8b2b1de22cab
Revises: 3b001e6abd5f
Create Date: 2023-09-07 21:48:40.966084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b2b1de22cab'
down_revision = '3b001e6abd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_table_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_time', schema=None) as batch_op:
        batch_op.drop_column('day_of_the_week')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_time', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_of_the_week', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('time_table_day')
    # ### end Alembic commands ###
