"""empty message

Revision ID: a87f68e5e5d9
Revises: ad610345daab
Create Date: 2023-08-28 18:17:49.651834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87f68e5e5d9'
down_revision = 'ad610345daab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('class_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_number', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
