"""empty message

Revision ID: cdceb46ddaaf
Revises: ef88cc205136
Create Date: 2023-09-30 22:23:12.488831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdceb46ddaaf'
down_revision = 'ef88cc205136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_table', schema=None) as batch_op:
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###
