"""empty message

Revision ID: eb8b6a33aa84
Revises: 2bd7e67886d8
Create Date: 2023-10-09 22:02:56.258882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8b6a33aa84'
down_revision = '2bd7e67886d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('over_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('account_type_id', sa.Integer(), nullable=True),
    sa.Column('payed', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deleted_over_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('over_head_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['over_head_id'], ['over_head.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_over_head')
    op.drop_table('over_head')
    # ### end Alembic commands ###
